name: Build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: demo
      - name: Cache cache-pip
        uses: actions/cache@v3
        with:
          path: cache-pip
          key: cache-pip-demo
      - name: inject cache-pip into docker
        uses: reproducible-containers/buildkit-cache-dance@v2.1.2
        with:
          cache-source: cache-pip
          cache-target: /root/.cache/pip
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
